name: react-native-android-build-apk
on:
  push:
    branches:
      - master
      jobs:
        build-android:
          runs-on: ubuntu-latest
          permissions:
            contents: write
          steps:
            - uses: actions/checkout@v3
            
            - name: Install npm dependencies
              run: npm install
              
            - name: Build Android Release
              run: cd android && ./gradlew assembleRelease
              
            - name: Read package.json
              uses: tyankatsu0105/read-package-version-actions@v1
              id: package-version
      
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: app-release.apk
                path: android/app/build/outputs/apk/release/
      
            - name: Create Github Release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "android/app/build/outputs/apk/release/app-release.apk"
                tag: "v${{ steps.package-version.outputs.version }}"
                replacesArtifacts: false
                token: ${{ secrets.GITHUB_TOKEN }}
                allowUpdates: true
